export { default as i18n } from './locale';
//export { default as Alert } from './alert';
export { default as Button } from './button';
// export { default as Layout } from './layout';
// export { default as Loading } from './loading';
// export { default as MessageBox } from './message-box';
// export { default as Notification } from './notification';
// export { default as Radio } from './radio';
// export { default as Dialog } from './dialog';
// export { default as Progress } from './progress';
// export { default as Tabs } from './tabs';
// export { default as Tree } from './tree';
// export { default as Input } from './input';
// export { default as Icon } from './icon';
// export { default as Menu } from './menu';
// export { default as Tooltip } from './tooltip';
// export { default as InputNumber } from './input-number';
// export { default as Checkbox } from './checkbox';
// export { default as Switch } from './switch';
// export { default as Tag } from './tag';
// export { default as Select } from './select';
// export { default as Pagination } from './pagination';
// export { default as AutoComplete } from './auto-complete';
// export { TimeSelect, TimePicker, TimeRangePicker, DatePicker, DateRangePicker } from './date-picker';
// export { default as Cascader } from './cascader';